version: '3'
services:
  app:
    build:
       context: ..
       dockerfile: Dockerfile  
    image: vscode-node-ts-sass
    container_name: vscode-node-ts-sass
    volumes:
      - ..:/home
    ports:     
       - 3000:3000
    command: sleep 365d