version: '3'
services:
  app:
    build:
       context: .
       dockerfile: Dockerfile  
    image: node-ts
    container_name: node-ts
    volumes:
      - .:/home
    ports:     
       - 3000:3000
    command: sleep infinity